In [1]:
import numpy as np

In [2]:
ls1 = [1, 2, 3, 4]
ls2 = [5, 6, 7, 8]

print(ls1 + ls2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [3]:
ls1 = np.array([1, 2, 3, 4])
ls2 = np.array([5, 6, 7, 8])

print(ls1 + ls2)

[ 6  8 10 12]


# Numpy Subsetting

In [7]:
# ls1 > 6
ls2[ls2 > 6]

array([7, 8])

# 2D Array

In [28]:
arr_2d = np.array([[1,2], [3, 4], [5, 6]])

# arr_2d.ndim
# arr_2d[1]
# arr_2d[0:2]

arr_2d[1, 1]


np.int64(4)

# <b> 3D Array </b>

In [ ]:
arr_3d = np.array([[[1, 2, 3], 
                    [4, 5, 6]],
                   
                   [[7, 8, 9],
                    [10, 11, 12]]])
# arr_3d.ndim

#For 3D: (Depth, Row, Column(Index))
arr_3d[1, 1, 2]

np.int64(12)

# NumPy Properties

In [41]:
ls1 = np.array([1, 2, 3, 4])
ls2 = np.array([5, 6, 7, 8])

ls1.shape
ls1.size
ls1.dtype

dtype('int64')

In [ ]:
ls2 = np.array([5, 6, 7, 8, 8, 9, 9, 9])
np.std(ls2)

ls2 = np.array([5, 6, 7, 8, 8, 9, 9, 9])
np.mode(ls2, 2)

np.float64(1.4086784586980805)

# Builtin Creation Method

In [46]:
np.zeros([2, 2]) #similarly i can do for ones
np.ones([2, 2]) 

array([[1., 1.],
       [1., 1.]])

In [6]:
from  datetime import datetime
st_date = datetime(2024, 1, 1) 
ed_date = datetime(2024, 12, 31)
n_days = (ed_date - st_date).days
n_days


365

In [ ]:
datelist = []
for i in range(n_days):
    datelist.append(st_date.date())
    st_date += timedelta(day=1)

In [ ]:
stk_price_ls = [np.random.rand(n_days).tolist()]
